"""Add document segments and refactor relationships

Revision ID: 622ebc07fe53
Revises: 0042d143b73e
Create Date: 2025-06-07 15:32:07.376255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622ebc07fe53'
down_revision: Union[str, None] = '0042d143b73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_segments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('document_id', sa.Integer(), nullable=False),
                    sa.Column('segment_type', sa.String(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('line_number', sa.Integer(), nullable=True),
                    sa.Column('page_number', sa.Integer(), nullable=True),
                    sa.Column('paragraph_index', sa.Integer(), nullable=True),
                    sa.Column('row_index', sa.Integer(), nullable=True),
                    sa.Column('character_start', sa.Integer(), nullable=True),
                    sa.Column('character_end', sa.Integer(), nullable=True),
                    sa.Column('additional_data', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['documents.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_document_segments_id'),
                    'document_segments', ['id'], unique=False)
    op.create_table('segment_codes',
                    sa.Column('segment_id', sa.Integer(), nullable=False),
                    sa.Column('code_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ),
                    sa.ForeignKeyConstraint(
                        ['segment_id'], ['document_segments.id'], ),
                    sa.PrimaryKeyConstraint('segment_id', 'code_id')
                    )
    op.add_column('annotations', sa.Column(
        'segment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'annotations', 'document_segments', [
                          'segment_id'], ['id'])
    op.add_column('quotes', sa.Column(
        'start_char', sa.Integer(), nullable=True))
    op.add_column('quotes', sa.Column('end_char', sa.Integer(), nullable=True))
    op.add_column('quotes', sa.Column('segment_id', sa.Integer(),
                  nullable=True))  # Make nullable initially
    op.drop_constraint(op.f('quotes_code_id_fkey'),
                       'quotes', type_='foreignkey')
    op.create_foreign_key(None, 'quotes', 'document_segments', [
                          'segment_id'], ['id'])
    op.drop_column('quotes', 'code_id')
    op.drop_column('quotes', 'end_position')
    op.drop_column('quotes', 'page_number')
    op.drop_column('quotes', 'line_number')
    op.drop_column('quotes', 'start_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('start_position',
                  sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotes', sa.Column(
        'line_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotes', sa.Column(
        'page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotes', sa.Column('end_position',
                  sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotes', sa.Column('code_id', sa.INTEGER(),
                  autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.create_foreign_key(op.f('quotes_code_id_fkey'),
                          'quotes', 'codes', ['code_id'], ['id'])
    op.drop_column('quotes', 'segment_id')
    op.drop_column('quotes', 'end_char')
    op.drop_column('quotes', 'start_char')
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.drop_column('annotations', 'segment_id')
    op.drop_table('segment_codes')
    op.drop_index(op.f('ix_document_segments_id'),
                  table_name='document_segments')
    op.drop_table('document_segments')
    # ### end Alembic commands ###
