"""removed raw_content_url from document

Revision ID: 81c8e639172f
Revises: d647b19592de
Create Date: 2025-06-10 13:23:10.039134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c8e639172f'
down_revision: Union[str, None] = 'd647b19592de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_content_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_content_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
