"""Add code_id foreign key to quotes table

Revision ID: c5401b765ffe
Revises: 98622f03dc19
Create Date: 2025-06-02 23:54:50.592983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5401b765ffe'
down_revision: Union[str, None] = '98622f03dc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('cloudinary_url', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotes', 'codes', ['code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'code_id')
    op.drop_column('documents', 'cloudinary_url')
    op.drop_column('documents', 'cloudinary_public_id')
    # ### end Alembic commands ###
